[package]
name = "silver_animation"
version = "0.1.0"
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quicksilver = {version="0.4.0-alpha0.4"}